/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedMoreSettingsRouteImport } from './routes/_authenticated/more/settings'
import { Route as AuthenticatedMoreExportRouteImport } from './routes/_authenticated/more/export'
import { Route as AuthenticatedMoreCommissionsRouteImport } from './routes/_authenticated/more/commissions'
import { Route as AuthenticatedMoreCloseRouteImport } from './routes/_authenticated/more/close'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoreSettingsRoute =
  AuthenticatedMoreSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMoreRoute,
  } as any)
const AuthenticatedMoreExportRoute = AuthenticatedMoreExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedMoreRoute,
} as any)
const AuthenticatedMoreCommissionsRoute =
  AuthenticatedMoreCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedMoreRoute,
  } as any)
const AuthenticatedMoreCloseRoute = AuthenticatedMoreCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => AuthenticatedMoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/more': typeof AuthenticatedMoreRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/today': typeof AuthenticatedTodayRoute
  '/more/close': typeof AuthenticatedMoreCloseRoute
  '/more/commissions': typeof AuthenticatedMoreCommissionsRoute
  '/more/export': typeof AuthenticatedMoreExportRoute
  '/more/settings': typeof AuthenticatedMoreSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/more': typeof AuthenticatedMoreRouteWithChildren
  '/new': typeof AuthenticatedNewRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/today': typeof AuthenticatedTodayRoute
  '/more/close': typeof AuthenticatedMoreCloseRoute
  '/more/commissions': typeof AuthenticatedMoreCommissionsRoute
  '/more/export': typeof AuthenticatedMoreExportRoute
  '/more/settings': typeof AuthenticatedMoreSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/more': typeof AuthenticatedMoreRouteWithChildren
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/more/close': typeof AuthenticatedMoreCloseRoute
  '/_authenticated/more/commissions': typeof AuthenticatedMoreCommissionsRoute
  '/_authenticated/more/export': typeof AuthenticatedMoreExportRoute
  '/_authenticated/more/settings': typeof AuthenticatedMoreSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/caja'
    | '/clients'
    | '/more'
    | '/new'
    | '/onboarding'
    | '/today'
    | '/more/close'
    | '/more/commissions'
    | '/more/export'
    | '/more/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/caja'
    | '/clients'
    | '/more'
    | '/new'
    | '/onboarding'
    | '/today'
    | '/more/close'
    | '/more/commissions'
    | '/more/export'
    | '/more/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/caja'
    | '/_authenticated/clients'
    | '/_authenticated/more'
    | '/_authenticated/new'
    | '/_authenticated/onboarding'
    | '/_authenticated/today'
    | '/_authenticated/more/close'
    | '/_authenticated/more/commissions'
    | '/_authenticated/more/export'
    | '/_authenticated/more/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/more/settings': {
      id: '/_authenticated/more/settings'
      path: '/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof AuthenticatedMoreSettingsRouteImport
      parentRoute: typeof AuthenticatedMoreRoute
    }
    '/_authenticated/more/export': {
      id: '/_authenticated/more/export'
      path: '/export'
      fullPath: '/more/export'
      preLoaderRoute: typeof AuthenticatedMoreExportRouteImport
      parentRoute: typeof AuthenticatedMoreRoute
    }
    '/_authenticated/more/commissions': {
      id: '/_authenticated/more/commissions'
      path: '/commissions'
      fullPath: '/more/commissions'
      preLoaderRoute: typeof AuthenticatedMoreCommissionsRouteImport
      parentRoute: typeof AuthenticatedMoreRoute
    }
    '/_authenticated/more/close': {
      id: '/_authenticated/more/close'
      path: '/close'
      fullPath: '/more/close'
      preLoaderRoute: typeof AuthenticatedMoreCloseRouteImport
      parentRoute: typeof AuthenticatedMoreRoute
    }
  }
}

interface AuthenticatedMoreRouteChildren {
  AuthenticatedMoreCloseRoute: typeof AuthenticatedMoreCloseRoute
  AuthenticatedMoreCommissionsRoute: typeof AuthenticatedMoreCommissionsRoute
  AuthenticatedMoreExportRoute: typeof AuthenticatedMoreExportRoute
  AuthenticatedMoreSettingsRoute: typeof AuthenticatedMoreSettingsRoute
}

const AuthenticatedMoreRouteChildren: AuthenticatedMoreRouteChildren = {
  AuthenticatedMoreCloseRoute: AuthenticatedMoreCloseRoute,
  AuthenticatedMoreCommissionsRoute: AuthenticatedMoreCommissionsRoute,
  AuthenticatedMoreExportRoute: AuthenticatedMoreExportRoute,
  AuthenticatedMoreSettingsRoute: AuthenticatedMoreSettingsRoute,
}

const AuthenticatedMoreRouteWithChildren =
  AuthenticatedMoreRoute._addFileChildren(AuthenticatedMoreRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRouteWithChildren
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRouteWithChildren,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
